CREATE MEMORY TABLE "PUBLIC"."TRADE_DETAILS"(
    "ID" BIGINT NOT NULL IDENTITY    PRIMARY KEY,
    "AMOUNT" DOUBLE,
    "DESCRIPTION" VARCHAR(255),
    "NAME" VARCHAR(255),
    "PRICE" DOUBLE,
    "SOLDOUT_MIN" VARCHAR(255),
    "THRESHOLD_MAX" VARCHAR(255)
);

-- ALTER TABLE "PUBLIC"."TRADE_DETAILS" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_7" PRIMARY KEY("ID");
INSERT INTO TRADE_DETAILS ("ID","AMOUNT", "DESCRIPTION", "NAME", "PRICE", "SOLDOUT_MIN","THRESHOLD_MAX") VALUES (1,102,'My Buyins1','infosys',99.5,'98','109');
INSERT INTO TRADE_DETAILS ("ID","AMOUNT", "DESCRIPTION", "NAME", "PRICE", "SOLDOUT_MIN","THRESHOLD_MAX") VALUES (2,105,'My Buyins2','apple',96.5,'97','111');
